public enum EventID
{
  
    NONE,
    //HOME SCRENE
    CHANGE_COIN = 50,
    CHANGE_HEART = 51,
    CHANGE_STAR = 52,
    CHANGE_AVATAR = 53,
    
    REFRESH_HOMESCENE = 100,
    
    ANTI_SPAM_NAVIGATION_BAR = 200,
    
    // HOME
    UPDATE_NOTIFY_DAILYLOGIN = 300,
    UPDATE_NOTIFY_DAILYREWARD = 301,
    UPDATE_TREASURE_PROGRESS = 302,
    
    // ADS
    REWARDED_ADS_COMPLETED = 1000,
    INTERSTITIAL_ADS_COMPLETED = 1001,
    
    //BOOSTER HOME SCENE
    HOME_BOOSTER_CHANGED = 1500,
    
    //BOOSTER GAMEPLAY
    ON_BOOSTER_CONDITION_CHANGED = 2000,
    ON_FROZE_BOOSTER_ENDED = 2001,
    //
    REQUEST_TAKE_ITEM_FROM_BOX = 3001,
    ITEM_PLACED_CORRECTLY = 3002,
    
    //Star Effect
    SPAWN_STAR = 4000,
    
    //Localization
    CHANGE_LOCALIZATION = 4000,
    
}
