public enum EventID
{
  
    NONE,
    //HOME SCRENE
    REFRESH_HOMESCENE = 100,
    
    ANTI_SPAM_NAVIGATION_BAR = 200,
    // ADS
    REWARDED_ADS_COMPLETED = 1000,
    INTERSTITIAL_ADS_COMPLETED = 1001,

}
