public enum EventID
{
  
    NONE,
    //HOME SCRENE
    CHANGE_COIN = 50,
    CHANGE_HEART = 51,
    CHANGE_STAR = 52,
    CHANGE_AVATAR = 53,
    
    REFRESH_HOMESCENE = 100,
    
    ANTI_SPAM_NAVIGATION_BAR = 200,
    
    UPDATE_NOTIFY_DAILYLOGIN = 300,
    UPDATE_NOTIFY_DAILYREWARD = 301,
    
    // ADS
    REWARDED_ADS_COMPLETED = 1000,
    INTERSTITIAL_ADS_COMPLETED = 1001,
    
    
    //BOOSTER
    CHANGE_BOXBUFFER_BOOSTER = 2000,
    CHANG_COMPASS_BOOSTER = 2001,
    CHANGE_FROZETIME_BOOSTER = 2002,
    CHANGE_HINT_BOOSTER = 2003,
    CHANGE_MAGICWAND_BOOSTER =  2004,
    CHANGE_MAGNET_BOOSTER = 2005,
    CHANGE_MAGNIFIER_BOOSTER = 2006,
    CHANGE_TIMEBUFFER_BOOSTER = 2007,
    CHANGE_X2STAR_BOOSTER = 2008,
}
